on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MatterFOSS web app
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16.4.2'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
